### ISSUE TITLE
Async tasks

### ISSUE THREAD

**Issue by idanarye** [idanarye/vim-omnipytent#5]
I want to be able to write "asynchronous tasks" - tasks that will do something, release Vim's event loop(to let the user and/or jobs do things), and then, when the event they wait for happen - continue the task from where it stopped.

Since Python only got coroutines at 3.5, and we want to support Python 2 and older versions of Python 3 - we'll use generators instead.

Examples of the desired syntax:

Open a JSON buffer, let the user write stuff in it, and once the user closes it - send a request with the JSON they wrote:
```python
@task
def send_json(ctx):
    CMD.new()
    OPT.buftype = 'nofile'
    CMD.setfiletype('json')
    buf = vim.current.buffer

    # This will return once the user closes the buffer
    yield wait_for_close(buf)

    send_json_to_server(json.loads('\n'.join(buf)))
```

`fzf` - we need to release the events loop because it runs in a terminal buffer:
```python
@task
def pick_something(ctx):
    lst = [item for item in things_we_want_to_pick_from() if pickable(item)]

    choice = yield FZF(lst)

    # Alternative:
    choice = yield some_cmd & FZF

    do_something_with(choice)
```

**Comment by idanarye** [comment]
The Idea
========
The task runner will become a generator. When it runs a generator task, it'll call `next()` on it and expect to get an object with a `async_wait()` method. It'll then register itself in a global dictionary with it's object id as key, convert that key to string(to avoid integer size problems), add the iteration number(to avoid re-awakening the same iteration) - and pass that _awakening token_ to `async_wait()`.

`async_wait()` is expected to register some event or callback on the Vim side. That event should call `omnipytent#async_notify()` with the awakening token given to `async_wait()`.

`omnipytent#async_notify()` will `pop()` the iterator from the global dictionary, verify it's iteration number, and call `async_notify()` on the object yielded from the task. Any extra arguments to `omnipytent#async_notify()` will be passed to `async_notify()`.

The value returned from `async_notify()`(could be `None`) will then be sent back to the iterator(with `send()`.

**Comment by idanarye** [comment]
Example:

```python
def get_text_from_buffer(filetype):
    CMD.new()
    OPT.buftype = 'nofile'
    OPT.filetype = filetype
    CMD.autocmd('BufDelete <buffer> call omnipytent#async_notify(b:omnipytent_awaitToken)')
    buf = vim.current.buffer

    class Callback:
        def async_wait(self, token):
            vim.current.buffer.vars['omnipytent_awaitToken'] = token

        def async_notify(self):
            return '\n'.join(buf)
```

Will be used like so:
```python
@task
def send_json(ctx):
    send_json_to_server(json.loads(yield get_text_from_buffer('json')))
```

**Comment by idanarye** [comment]
Already did it, forgot to close...

**Comment by lervag** [comment]
I might be asking a silly question, but does this mean that Omnipytent now supports asynchronous tasks in the sense that we can start a test suit (e.g. `pytest`) in the background and have it open a quickfix buffer or a buffer that displays the errors/warnings when it is finished?

**Comment by idanarye** [comment]
Well, yes... and no. The architecture now supports this, but I have not implemented such functionality yet. I just opened a ticket for it - #9.

**Comment by lervag** [comment]
Great, I look forward to seing it added!
