### ISSUE TITLE
Add async commands for running things in the background

### ISSUE THREAD

**Issue by idanarye** [idanarye/vim-omnipytent#9]
The current `AsyncCommand`s are UI-centric - `INPUT_BUFFER` for a text buffer that serves as a text area and `SelectionUI` (with `CHOOSE` as a facade) for picking options from a list. But this mechanism [can be used for what the Vim community means when it says "async"](https://github.com/idanarye/vim-omnipytent/issues/5#issuecomment-475046841) - the act of running an external program in the background, releasing Vim's event loop, and when that program finishes acting on its results.

To this end, we'll want a new `ShellCommandExecuter` called `JOB`. It'll work similar to `TERMINAL_TAB` and `TERMINAL_PANEL` but will create a background job (without a TTY) instead. It'll model it after Python's `Popen`, so it'll have two methods that return `AsyncCommand`s - `wait` and `communicate` - where:
* `wait` returns the exit code:
    ```python
    job = JOB('py.test', './tests')
    exit_code = yield job.wait()
    out = job.stdout
    err = job.stderr
    ```
 * `communicate` returns a tuple of stdout and stderr:
    ```python
    job = JOB('py.test', './tests')
    out, err = yield job.communicate()
    exit_code = job.returncode
    ```

### Open questions
1. Maybe also add a method for returning all 3? `Popen` does not have anything like that - what should I name it? Plumbum has `run()`, which works on the command object - not the process object - but that's close enough:
    ```python
    job = JOB('py.test', './tests')
    exit_code, out, err = yield job.run()
    exit_code = job.returncode
    ```
2. Speaking of Plumbum - it has a `retcode` argument for deciding which exit status to expect and throws `ProcessExecutionError` otherwise. Maybe I can use that too (but throw `subprocess.CalledProcessError` instead)? The default value should still be `retcode=None` though...
3. Should I also add a facility for reading line-by-line? The problem is that I can't make a nice async loop syntax - AFAIK Python doesn't have anything like this, not even at the newest version - so it'll have to be something ugly like:
    ```python
    job = JOB('py.test', './tests')
    iter_lines = job.iter_lines()
    while (yield iter_lines):
	for out_line, err_line in iter_lines:
	    ...
    ```

**Comment by lervag** [comment]
I'm happy to see this on the roadmap!

1. Would there be any difference between `job.wait` and `job.communicate` other than their return values? If not, then I would propose to only use a single method ala `jo.run`.

2. Unfortunately I have no experience with Plumbum, and so I have no intput on this matter.

3. I am not sure what a "nice async loop syntax" looks like. To me, what you propose actually looks quite good. And in any case, I think the most important part now would be to add something like `job.wait` or `job.run`. As I wrote in another thread, my personal use case would be to start a compilation or test suite in the background and have it open a quickfix list or an output buffer when it was finished.

**Comment by idanarye** [comment]
> Would there be any difference between job.wait and job.communicate other than their return values? If not, then I would propose to only use a single method ala jo.run.

Good point. I've named them after the methods in Python's `Popen`, but there there is the difference of `communicate` reading the standard streams and `wait` not reading them. Since Neovim's model does not allow invoking a read from a job (you need to use the `on_stderr` and `on_stdout` hooks), I can't do it like this, so they won't have any difference and having a single `run()` method will be enough.

I could also simplify things and make the job object itself an `AsyncCommand` that returns results in itself:

```python
job_result = yield JOB('py.test', './tests')
exit_code = job_result.returncode
out = job_result.stdout
err = job_result.stderr
```

Once we have that, it should be easy to add `wait`, `communicate` and `run` as simple wrappers. Though I doubt that would be necessary.

> I am not sure what a "nice async loop syntax" looks like

A `for` loop that `yield`s on every iteartion. Even if we were using Python's `async`/`await` keywords, this would still not do:
```python
for foo in await bar():
    ...
```

Because the containing coroutine would yield on when evaluating `async bar()` and then run the entire `for` loop without yielding (unless you yield in the body). But if it had something like:
```python
await for in bar():
    ...
```

That would desugar to something like:
```python
it = iter(bar())
while True:
    try:
	foo = await it.__async_next__()
    except StopIteration:
        break
    ...
```
Then the loop could process the items of `bar()` as an asynchronous stream, yielding execution back to the reactor when it waits for `bar()` to produce more entries.

**Comment by lervag** [comment]
Ok, I think I understand. As said, I'll be glad to test this when it is getting ready. :)

**Comment by lervag** [comment]
Great, I've just made some initial tests and it looks like this does exactly what I want! Thanks!

**Comment by idanarye** [comment]
Now I just need to create some wrappers...
